### ISSUE TITLE
Up for adoption?

### ISSUE THREAD

**Issue by patocallaghan** [amkirwan/ember-oauth2#38]
When an original owner no longer has time to maintain the addon, there is a place where the addon can be "put up for adoption." Melanie Sumner has created [adopted-ember-addons](https://github.com/adopted-ember-addons).

Would you consider allowing us to adopt ember-oauth2 so that the addon may continue to provide useful service to the community?

There are currently [two open PRs](https://github.com/amkirwan/ember-oauth2/pulls) (which have been open for a while) that would be useful to people.

**Comment by amkirwan** [comment]
@patocallaghan I can update the add-on I didn't realize anyone was actually using it still. I am just no longer actively working with Ember regularly unfortunately so the add-on isn't on my radar. 

I reviewed the PR you mentioned. I'll merge once the changes are submitted.

**Comment by patocallaghan** [comment]
@amkirwan Sure, that's no problem. If you don't want to put the addon up for adoption feel free to close the issue.

On the other hand, if you don't want the burden of maintaining this addon the Ember community would be happy to.

**Comment by amkirwan** [comment]
sounds good :

**Comment by patocallaghan** [comment]
Cool 👍 These are steps to make this happen https://github.com/adopted-ember-addons/program-guidelines/blob/master/README.md
